[workspace]
resolver = "3"
members = [
    "rzip-browser", 
    "rzip-cli", 
    "rzip-core", 
    "rzip-crypto", 
    "rzip-network", 
    "rzip-storage", 
    "rzip-verifiable"
]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1