[package]
name = "szip-rescomply-core"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "*"
chrono = { version = "*", features = ["serde"] }
serde = { version = "*", features = ["derive"] }
sha3 = "0.10"
hex = "0.4"
thiserror = "1.0"